// TODO: Import your actual images here once you add them to the assets folder
// import imgAmistar from '../assets/products/amistar.png';
// import imgBhindi from '../assets/products/bhindi.png';
// import imgIffco from '../assets/products/iffco.png';
// import imgConfidor from '../assets/products/confidor.png';
// import imgSaaf from '../assets/products/saaf.png';
// import imgTomato from '../assets/products/tomato.png';

export const BEST_DEALS = [
  {
    id: 1,
    name: 'Syngenta Amistar Top Fungicide',
    // imageUrl: imgAmistar, // Uncomment this line when the image is ready
    category: 'Fungicide',
    price: 780,
    originalPrice: 950,
    rating: 4.5,
    reviewCount: 128,
    weightOptions: ['100 ml', '250 ml', '500 ml', '1 Litre'],
    defaultWeight: '250 ml',
  },
  {
    id: 2,
    name: 'Mahyco Bhindi F1 Hybrid Seeds',
    // imageUrl: imgBhindi, // Uncomment this line when the image is ready
    category: 'Vegetable Seeds',
    price: 320,
    originalPrice: 400,
    rating: 4.7,
    reviewCount: 214,
    weightOptions: ['10 grams', '25 grams', '50 grams', '100 grams'],
    defaultWeight: '25 grams',
  },
  {
    id: 3,
    name: 'IFFCO NPK 19:19:19 Fertilizer',
    // imageUrl: imgIffco, // Uncomment this line when the image is ready
    category: 'Crop Nutrition',
    price: 560,
    originalPrice: 680,
    rating: 4.6,
    reviewCount: 97,
    weightOptions: ['500 grams', '1 kg', '5 kg', '25 kg', '50 kg'],
    defaultWeight: '1 kg',
  },
  {
    id: 4,
    name: 'Bayer Confidor Insecticide',
    // imageUrl: imgConfidor, // Uncomment this line when the image is ready
    category: 'Insecticide',
    price: 445,
    originalPrice: 530,
    rating: 4.4,
    reviewCount: 163,
    weightOptions: ['100 ml', '250 ml', '500 ml', '1 Litre'],
    defaultWeight: '250 ml',
  },
  {
    id: 5,
    name: 'UPL Saaf Carbendazim Fungicide',
    // imageUrl: imgSaaf, // Uncomment this line when the image is ready
    category: 'Fungicide',
    price: 210,
    originalPrice: 270,
    rating: 4.3,
    reviewCount: 89,
    weightOptions: ['100 grams', '250 grams', '500 grams', '1 kg'],
    defaultWeight: '250 grams',
  },
  {
    id: 6,
    name: 'Seminis Tomato F1 Hybrid Seeds',
    // imageUrl: imgTomato, // Uncomment this line when the image is ready
    category: 'Vegetable Seeds',
    price: 890,
    originalPrice: 1100,
    rating: 4.8,
    reviewCount: 302,
    weightOptions: ['5 grams', '10 grams', '25 grams', '50 grams', '100 grams'],
    defaultWeight: '10 grams',
  },
];

export const VEGETABLE_SEEDS = [
  {
    id: 101,
    name: 'Seminis Tomato Abhilash F1 Seeds',
    category: 'Tomato Seeds',
    price: 390,
    originalPrice: 500,
    rating: 4.8,
    reviewCount: 312,
    weightOptions: ['5 grams', '10 grams', '25 grams', '50 grams', '100 grams'],
    defaultWeight: '10 grams',
  },
  {
    id: 102,
    name: 'VNR Bhindi (Okra) Hybrid Seeds',
    category: 'Bhindi Seeds',
    price: 175,
    originalPrice: 240,
    rating: 4.5,
    reviewCount: 198,
    weightOptions: ['50 grams', '100 grams', '250 grams', '500 grams'],
    defaultWeight: '100 grams',
  },
  {
    id: 103,
    name: 'Sakata Chilli F1 Hybrid Seeds',
    category: 'Chilli Seeds',
    price: 510,
    originalPrice: 650,
    rating: 4.6,
    reviewCount: 143,
    weightOptions: ['5 grams', '10 grams', '25 grams', '50 grams'],
    defaultWeight: '10 grams',
  },
  {
    id: 104,
    name: 'Clause Cauliflower Snowball Seeds',
    category: 'Cauliflower Seeds',
    price: 280,
    originalPrice: 360,
    rating: 4.4,
    reviewCount: 87,
    weightOptions: ['10 grams', '25 grams', '50 grams', '100 grams'],
    defaultWeight: '25 grams',
  },
  {
    id: 105,
    name: 'Mahyco Bitter Gourd Hybrid Seeds',
    category: 'Bitter Gourd Seeds',
    price: 220,
    originalPrice: 290,
    rating: 4.3,
    reviewCount: 76,
    weightOptions: ['10 grams', '25 grams', '50 grams', '100 grams'],
    defaultWeight: '25 grams',
  },
  {
    id: 106,
    name: 'Advanta Bottle Gourd F1 Seeds',
    category: 'Bottle Gourd Seeds',
    price: 195,
    originalPrice: 260,
    rating: 4.5,
    reviewCount: 104,
    weightOptions: ['10 grams', '25 grams', '50 grams', '100 grams'],
    defaultWeight: '25 grams',
  },
];

/* ─── Crop Protection Deals Data ────────────────────────── */
export const CROP_PROTECTION_DEALS = [
  {
    id: 201,
    name: 'Syngenta Amistar Top Fungicide',
    category: 'Fungicide',
    price: 780,
    originalPrice: 950,
    rating: 4.7,
    reviewCount: 241,
    weightOptions: ['100 ml', '250 ml', '500 ml', '1 Litre'],
    defaultWeight: '250 ml',
  },
  {
    id: 202,
    name: 'Bayer Confidor Imidacloprid Insecticide',
    category: 'Insecticide',
    price: 445,
    originalPrice: 570,
    rating: 4.5,
    reviewCount: 183,
    weightOptions: ['100 ml', '250 ml', '500 ml', '1 Litre'],
    defaultWeight: '250 ml',
  },
  {
    id: 203,
    name: 'UPL Saaf Carbendazim + Mancozeb',
    category: 'Fungicide',
    price: 210,
    originalPrice: 280,
    rating: 4.4,
    reviewCount: 129,
    weightOptions: ['100 grams', '250 grams', '500 grams', '1 kg'],
    defaultWeight: '250 grams',
  },
  {
    id: 204,
    name: 'Dhanuka Targa Super Herbicide',
    category: 'Herbicide',
    price: 360,
    originalPrice: 450,
    rating: 4.3,
    reviewCount: 97,
    weightOptions: ['250 ml', '500 ml', '1 Litre'],
    defaultWeight: '500 ml',
  },
  {
    id: 205,
    name: 'BASF Cabrio Top Fungicide',
    category: 'Fungicide',
    price: 890,
    originalPrice: 1100,
    rating: 4.6,
    reviewCount: 154,
    weightOptions: ['100 grams', '250 grams', '500 grams'],
    defaultWeight: '250 grams',
  },
  {
    id: 206,
    name: 'Adama Bio Insecticide Neem Oil',
    category: 'Bio Pesticide',
    price: 320,
    originalPrice: 400,
    rating: 4.5,
    reviewCount: 112,
    weightOptions: ['250 ml', '500 ml', '1 Litre', '5 Litre'],
    defaultWeight: '500 ml',
  },
];

/* ─── Flower Seeds Data ──────────────────────────────── */
export const FLOWER_SEEDS = [
  {
    id: 301,
    name: 'Seminis Marigold African Giant Seeds',
    category: 'Marigold Seeds',
    price: 150,
    originalPrice: 200,
    rating: 4.7,
    reviewCount: 278,
    weightOptions: ['5 grams', '10 grams', '25 grams', '50 grams', '100 grams'],
    defaultWeight: '10 grams',
  },
  {
    id: 302,
    name: 'VNR Zinnia Double Mixed Colour',
    category: 'Zinnia Seeds',
    price: 120,
    originalPrice: 160,
    rating: 4.5,
    reviewCount: 142,
    weightOptions: ['5 grams', '10 grams', '25 grams', '50 grams'],
    defaultWeight: '10 grams',
  },
  {
    id: 303,
    name: 'Clause Petunia F1 Multiflora',
    category: 'Petunia Seeds',
    price: 480,
    originalPrice: 620,
    rating: 4.6,
    reviewCount: 95,
    weightOptions: ['100 seeds', '250 seeds', '500 seeds'],
    defaultWeight: '100 seeds',
  },
  {
    id: 304,
    name: 'Sakata Sunflower Hybrid Seeds',
    category: 'Sunflower Seeds',
    price: 190,
    originalPrice: 250,
    rating: 4.4,
    reviewCount: 188,
    weightOptions: ['10 grams', '25 grams', '50 grams', '100 grams', '250 grams'],
    defaultWeight: '25 grams',
  },
  {
    id: 305,
    name: 'Advanta Dahlia Mixed Colour Seeds',
    category: 'Dahlia Seeds',
    price: 210,
    originalPrice: 280,
    rating: 4.3,
    reviewCount: 67,
    weightOptions: ['5 grams', '10 grams', '25 grams'],
    defaultWeight: '10 grams',
  },
  {
    id: 306,
    name: 'Mahyco Cosmos Sensation Mixed Seeds',
    category: 'Cosmos Seeds',
    price: 95,
    originalPrice: 130,
    rating: 4.5,
    reviewCount: 113,
    weightOptions: ['5 grams', '10 grams', '25 grams', '50 grams'],
    defaultWeight: '10 grams',
  },
];

/* ─── Crop Nutrition Deals Data ────────────────────────── */
export const CROP_NUTRITION_DEALS = [
  {
    id: 401,
    name: 'IFFCO NPK 19:19:19 Water Soluble Fertilizer',
    category: 'Water Soluble NPK',
    price: 560,
    originalPrice: 720,
    rating: 4.7,
    reviewCount: 319,
    weightOptions: ['500 grams', '1 kg', '5 kg', '25 kg', '50 kg'],
    defaultWeight: '1 kg',
  },
  {
    id: 402,
    name: 'Coromandel Multi-K Potassium Nitrate',
    category: 'Potassium Fertilizer',
    price: 420,
    originalPrice: 550,
    rating: 4.5,
    reviewCount: 174,
    weightOptions: ['500 grams', '1 kg', '5 kg', '25 kg'],
    defaultWeight: '1 kg',
  },
  {
    id: 403,
    name: 'Godrej Agrovet Humesol Humic Acid',
    category: 'Bio Stimulant',
    price: 310,
    originalPrice: 400,
    rating: 4.4,
    reviewCount: 128,
    weightOptions: ['250 ml', '500 ml', '1 Litre', '5 Litre'],
    defaultWeight: '500 ml',
  },
  {
    id: 404,
    name: 'Bayer Fertimax Zinc Sulphate',
    category: 'Micronutrient',
    price: 185,
    originalPrice: 240,
    rating: 4.3,
    reviewCount: 96,
    weightOptions: ['500 grams', '1 kg', '5 kg', '25 kg'],
    defaultWeight: '1 kg',
  },
  {
    id: 405,
    name: 'Mahindra Agri Boron 20% Fertilizer',
    category: 'Micronutrient',
    price: 260,
    originalPrice: 340,
    rating: 4.5,
    reviewCount: 111,
    weightOptions: ['250 grams', '500 grams', '1 kg', '5 kg'],
    defaultWeight: '500 grams',
  },
  {
    id: 406,
    name: 'Syngenta Calbit C Calcium Boron',
    category: 'Liquid Fertilizer',
    price: 490,
    originalPrice: 630,
    rating: 4.6,
    reviewCount: 143,
    weightOptions: ['250 ml', '500 ml', '1 Litre', '5 Litre'],
    defaultWeight: '500 ml',
  },
];

/* ─── Insecticides Deals Data ──────────────────────────── */
export const INSECTICIDES_DEALS = [
  {
    id: 501,
    name: 'Bayer Confidor 200 SL Imidacloprid',
    category: 'Systemic Insecticide',
    price: 620,
    originalPrice: 790,
    rating: 4.7,
    reviewCount: 284,
    weightOptions: ['100 ml', '250 ml', '500 ml', '1 Litre'],
    defaultWeight: '250 ml',
  },
  {
    id: 502,
    name: 'Syngenta Actara 25 WG Thiamethoxam',
    category: 'Insecticide',
    price: 480,
    originalPrice: 620,
    rating: 4.6,
    reviewCount: 197,
    weightOptions: ['100 grams', '250 grams', '500 grams', '1 kg'],
    defaultWeight: '250 grams',
  },
  {
    id: 503,
    name: 'UPL Lancer Gold Acephate 50%',
    category: 'Contact Insecticide',
    price: 350,
    originalPrice: 450,
    rating: 4.4,
    reviewCount: 143,
    weightOptions: ['100 grams', '250 grams', '500 grams', '1 kg'],
    defaultWeight: '250 grams',
  },
  {
    id: 504,
    name: 'Dhanuka Tafgor Dimethoate 30%',
    category: 'Organophosphate',
    price: 270,
    originalPrice: 350,
    rating: 4.3,
    reviewCount: 108,
    weightOptions: ['250 ml', '500 ml', '1 Litre', '5 Litre'],
    defaultWeight: '500 ml',
  },
  {
    id: 505,
    name: 'BASF Regent 50 SC Fipronil',
    category: 'Phenylpyrazole',
    price: 890,
    originalPrice: 1100,
    rating: 4.6,
    reviewCount: 162,
    weightOptions: ['100 ml', '250 ml', '500 ml', '1 Litre'],
    defaultWeight: '250 ml',
  },
  {
    id: 506,
    name: 'Adama Neostar Neo-Nicotinoid Spray',
    category: 'Bio Insecticide',
    price: 310,
    originalPrice: 400,
    rating: 4.5,
    reviewCount: 119,
    weightOptions: ['250 ml', '500 ml', '1 Litre', '5 Litre'],
    defaultWeight: '500 ml',
  },
];

/* ─── Fungicides Deals Data ────────────────────────────── */
export const FUNGICIDES_DEALS = [
  {
    id: 601,
    name: 'Syngenta Amistar Top Azoxystrobin',
    category: 'Systemic Fungicide',
    price: 780,
    originalPrice: 980,
    rating: 4.8,
    reviewCount: 326,
    weightOptions: ['100 ml', '250 ml', '500 ml', '1 Litre'],
    defaultWeight: '250 ml',
  },
  {
    id: 602,
    name: 'UPL Saaf Carbendazim 12% + Mancozeb 63%',
    category: 'Broad Spectrum Fungicide',
    price: 210,
    originalPrice: 280,
    rating: 4.5,
    reviewCount: 241,
    weightOptions: ['100 grams', '250 grams', '500 grams', '1 kg'],
    defaultWeight: '250 grams',
  },
  {
    id: 603,
    name: 'BASF Cabrio Top Pyraclostrobin',
    category: 'Preventive Fungicide',
    price: 920,
    originalPrice: 1150,
    rating: 4.6,
    reviewCount: 178,
    weightOptions: ['100 grams', '250 grams', '500 grams'],
    defaultWeight: '250 grams',
  },
  {
    id: 604,
    name: 'Bayer Nativo Tebuconazole + Trifloxystrobin',
    category: 'Systemic Fungicide',
    price: 650,
    originalPrice: 820,
    rating: 4.7,
    reviewCount: 154,
    weightOptions: ['100 grams', '250 grams', '500 grams', '1 kg'],
    defaultWeight: '250 grams',
  },
  {
    id: 605,
    name: 'Dhanuka Dhanucop Copper Oxychloride 50%',
    category: 'Contact Fungicide',
    price: 180,
    originalPrice: 240,
    rating: 4.3,
    reviewCount: 112,
    weightOptions: ['250 grams', '500 grams', '1 kg', '5 kg'],
    defaultWeight: '500 grams',
  },
  {
    id: 606,
    name: 'Adama Hexadhan Hexaconazole 5% SC',
    category: 'Ergosterol Inhibitor',
    price: 340,
    originalPrice: 440,
    rating: 4.4,
    reviewCount: 98,
    weightOptions: ['100 ml', '250 ml', '500 ml', '1 Litre'],
    defaultWeight: '250 ml',
  },
];

/* ─── Herbicides Deals Data ────────────────────────────── */
export const HERBICIDES_DEALS = [
  {
    id: 701,
    name: 'Syngenta Gramoxone Paraquat 24% SL',
    category: 'Non-Selective Herbicide',
    price: 480,
    originalPrice: 620,
    rating: 4.6,
    reviewCount: 231,
    weightOptions: ['250 ml', '500 ml', '1 Litre', '5 Litre'],
    defaultWeight: '500 ml',
  },
  {
    id: 702,
    name: 'Bayer Nominee Gold Bispyribac Sodium',
    category: 'Selective Herbicide',
    price: 720,
    originalPrice: 900,
    rating: 4.7,
    reviewCount: 178,
    weightOptions: ['100 ml', '250 ml', '500 ml', '1 Litre'],
    defaultWeight: '250 ml',
  },
  {
    id: 703,
    name: 'UPL Roundup Glyphosate 41% SL',
    category: 'Post-emergent Herbicide',
    price: 310,
    originalPrice: 400,
    rating: 4.5,
    reviewCount: 296,
    weightOptions: ['500 ml', '1 Litre', '5 Litre'],
    defaultWeight: '1 Litre',
  },
  {
    id: 704,
    name: 'Dhanuka Targa Super Quizalofop',
    category: 'Graminicide',
    price: 360,
    originalPrice: 460,
    rating: 4.3,
    reviewCount: 119,
    weightOptions: ['250 ml', '500 ml', '1 Litre'],
    defaultWeight: '500 ml',
  },
  {
    id: 705,
    name: 'BASF Stomp Aqua Pendimethalin',
    category: 'Pre-emergent Herbicide',
    price: 540,
    originalPrice: 690,
    rating: 4.5,
    reviewCount: 143,
    weightOptions: ['250 ml', '500 ml', '1 Litre', '5 Litre'],
    defaultWeight: '500 ml',
  },
  {
    id: 706,
    name: 'Adama Weedmar Super 2,4-D Amine',
    category: 'Selective Herbicide',
    price: 195,
    originalPrice: 260,
    rating: 4.4,
    reviewCount: 87,
    weightOptions: ['500 ml', '1 Litre', '5 Litre'],
    defaultWeight: '1 Litre',
  },
];

/* ─── Bio Insecticides Deals Data ────────────────────────── */
export const BIO_INSECTICIDES_DEALS = [
  {
    id: 801,
    name: 'Bioneem Plus Azadirachtin 1500 ppm',
    category: 'Neem Based',
    price: 280,
    originalPrice: 370,
    rating: 4.6,
    reviewCount: 312,
    weightOptions: ['250 ml', '500 ml', '1 Litre', '5 Litre'],
    defaultWeight: '500 ml',
  },
  {
    id: 802,
    name: 'Multiplex Metarhizium Bio Insecticide',
    category: 'Fungal Bio-agent',
    price: 340,
    originalPrice: 440,
    rating: 4.5,
    reviewCount: 147,
    weightOptions: ['250 grams', '500 grams', '1 kg', '5 kg'],
    defaultWeight: '500 grams',
  },
  {
    id: 803,
    name: 'Godrej Beauveria Bassiana Spray',
    category: 'Entomopathogen',
    price: 390,
    originalPrice: 510,
    rating: 4.4,
    reviewCount: 98,
    weightOptions: ['250 ml', '500 ml', '1 Litre'],
    defaultWeight: '500 ml',
  },
  {
    id: 804,
    name: 'PI Industries Spinosad 45% SC',
    category: 'Microbial Insecticide',
    price: 720,
    originalPrice: 920,
    rating: 4.7,
    reviewCount: 183,
    weightOptions: ['100 ml', '250 ml', '500 ml', '1 Litre'],
    defaultWeight: '250 ml',
  },
  {
    id: 805,
    name: 'Biostadt Verticillium Lecanii Powder',
    category: 'Bio Fungal Agent',
    price: 260,
    originalPrice: 340,
    rating: 4.3,
    reviewCount: 76,
    weightOptions: ['250 grams', '500 grams', '1 kg'],
    defaultWeight: '500 grams',
  },
  {
    id: 806,
    name: 'Koppert BV Trichoderma Harzianum',
    category: 'Soil Bio-agent',
    price: 310,
    originalPrice: 400,
    rating: 4.5,
    reviewCount: 121,
    weightOptions: ['250 grams', '500 grams', '1 kg', '5 kg'],
    defaultWeight: '500 grams',
  },
];

/* ─── Tools & Equipment Deals Data ──────────────────────── */
export const TOOLS_EQUIPMENT_DEALS = [
  {
    id: 901,
    name: 'Knapsack Battery Operated Sprayer 16L',
    category: 'Sprayer',
    price: 2800,
    originalPrice: 3600,
    rating: 4.6,
    reviewCount: 284,
    weightOptions: ['1 Piece'],
    defaultWeight: '1 Piece',
  },
  {
    id: 902,
    name: 'Wolf Garten Stainless Steel Trowel Set',
    category: 'Hand Tools',
    price: 1150,
    originalPrice: 1500,
    rating: 4.5,
    reviewCount: 176,
    weightOptions: ['1 Piece', '2 Piece Set', '5 Piece Set'],
    defaultWeight: '2 Piece Set',
  },
  {
    id: 903,
    name: 'Honda Power Weeder FJ500',
    category: 'Power Weeder',
    price: 38500,
    originalPrice: 48000,
    rating: 4.8,
    reviewCount: 93,
    weightOptions: ['1 Unit'],
    defaultWeight: '1 Unit',
  },
  {
    id: 904,
    name: 'Plastic Garden Cultivator Weeder',
    category: 'Weeder',
    price: 320,
    originalPrice: 420,
    rating: 4.3,
    reviewCount: 231,
    weightOptions: ['1 Piece', '3 Piece Set'],
    defaultWeight: '1 Piece',
  },
  {
    id: 905,
    name: 'Stihl FS 38 Petrol Brush Cutter',
    category: 'Brush Cutter',
    price: 14500,
    originalPrice: 18000,
    rating: 4.7,
    reviewCount: 118,
    weightOptions: ['1 Unit'],
    defaultWeight: '1 Unit',
  },
  {
    id: 906,
    name: 'Safety Nitrile Hand Gloves Pack',
    category: 'Safety Equipment',
    price: 180,
    originalPrice: 250,
    rating: 4.4,
    reviewCount: 342,
    weightOptions: ['Small', 'Medium', 'Large', 'XL'],
    defaultWeight: 'Medium',
  },
];

/* ─── Plants Deals Data ──────────────────────────────── */
export const PLANTS_DEALS = [
  {
    id: 1001,
    name: 'Grafted Mango Alphonso Sapling',
    category: 'Fruit Plant',
    price: 350,
    originalPrice: 450,
    rating: 4.7,
    reviewCount: 231,
    weightOptions: ['1 Plant', '2 Plants', '5 Plants', '10 Plants'],
    defaultWeight: '1 Plant',
  },
  {
    id: 1002,
    name: 'Curry Leaf Plant (Kadipatta)',
    category: 'Herb Plant',
    price: 80,
    originalPrice: 120,
    rating: 4.5,
    reviewCount: 418,
    weightOptions: ['1 Plant', '3 Plants', '5 Plants'],
    defaultWeight: '1 Plant',
  },
  {
    id: 1003,
    name: 'Grafted Guava L-49 Sapling',
    category: 'Fruit Plant',
    price: 180,
    originalPrice: 240,
    rating: 4.6,
    reviewCount: 176,
    weightOptions: ['1 Plant', '2 Plants', '5 Plants', '10 Plants'],
    defaultWeight: '1 Plant',
  },
  {
    id: 1004,
    name: 'Aloe Vera Medicinal Plant',
    category: 'Medicinal Plant',
    price: 60,
    originalPrice: 90,
    rating: 4.4,
    reviewCount: 523,
    weightOptions: ['1 Plant', '5 Plants', '10 Plants', '25 Plants'],
    defaultWeight: '5 Plants',
  },
  {
    id: 1005,
    name: 'Lemon (Nimbu) Grafted Plant',
    category: 'Citrus Plant',
    price: 120,
    originalPrice: 160,
    rating: 4.5,
    reviewCount: 289,
    weightOptions: ['1 Plant', '2 Plants', '5 Plants'],
    defaultWeight: '1 Plant',
  },
  {
    id: 1006,
    name: 'Rose Ornamental Grafted Plant',
    category: 'Ornamental Plant',
    price: 150,
    originalPrice: 200,
    rating: 4.6,
    reviewCount: 194,
    weightOptions: ['1 Plant', '3 Plants', '5 Plants'],
    defaultWeight: '1 Plant',
  },
];



export const ALL_STATIC_PRODUCTS = [
  ...BEST_DEALS,
  ...VEGETABLE_SEEDS,
  ...CROP_PROTECTION_DEALS,
  ...FLOWER_SEEDS,
  ...CROP_NUTRITION_DEALS,
  ...INSECTICIDES_DEALS,
  ...FUNGICIDES_DEALS,
  ...HERBICIDES_DEALS,
  ...BIO_INSECTICIDES_DEALS,
  ...TOOLS_EQUIPMENT_DEALS,
  ...PLANTS_DEALS
];
